- name: Create new droplet
  hosts: localhost
  become: yes
  
  vars:
    public_key : "76:ae:9d:1b:49:fa:e3:9c:00:91:f9:9e:c9:0c:93:85"
  
  tasks: 
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        api_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        state: active
        project: first-project
        name: "{{ droplet_name }}"
        region: nyc3
        image: centos-stream-9-x64
        size: "{{ droplet_size | default('s-1vcpu-2gb') }}"
        wait_timeout: 500
        ssh_keys: [ "{{ public_key }}" ]
      register: my_droplet
    - name: Display droplet
      ansible.builtin.debug:
        msg: "{{ my_droplet }}" 
    - name: Display IP address
      ansible.builtin.debug:
        msg: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}" 